# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app
# Copy requirements.txt and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
ARG SECRET_KEY
ARG EMAIL_HOST_PASSWORD

ENV SECRET_KEY=$SECRET_KEY
ENV EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
# Copy the rest of the application code
COPY ./app

# Set environment variables
ENV PORT 8080

CMD guincorn -- bind :$PORT --TrainingManagementSystem.wsgi:application

# # Expose port 8080
# EXPOSE 8080
# # Expose the port the app runs on
# EXPOSE 8000
# # Run Django migrations and start the application
# CMD ["sh", "-c","gunicorn", "--bind", "TrainingManagmentSystem.wsgi.application",":8080","python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
