# Generated by Django 5.0.7 on 2024-07-31 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0002_traineeprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="traineeprogress",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="trainingmodule",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="Training/uploads/"
            ),
        ),
        migrations.CreateModel(
            name="Trainingdocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documentname", models.CharField(max_length=100)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="Training/ATTENDANCE SHEET"
                    ),
                ),
                ("Documentdomain", models.CharField(max_length=20)),
                ("facility", models.CharField(max_length=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "trainee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Training.trainingmodule",
                    ),
                ),
            ],
        ),
    ]
