# Generated by Django 5.0.7 on 2024-08-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0003_traineeprogress_date_alter_trainingmodule_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traineeprogress",
            name="progress",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
