# Generated by Django 5.0.7 on 2024-08-03 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0004_alter_traineeprogress_progress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="traineeprogress",
            name="progress",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="traineeprogress",
            name="trainee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="traineeprogress",
            unique_together={("trainee", "training_module")},
        ),
    ]
