# Generated by Django 5.0.7 on 2024-08-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0005_alter_traineeprogress_progress_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainingdocuments",
            old_name="Documentdomain",
            new_name="document_domain",
        ),
        migrations.AddField(
            model_name="trainingdocuments",
            name="unique_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="trainingdocuments",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="Training/ATTENDANCE_SHEET/"
            ),
        ),
        migrations.AlterField(
            model_name="trainingdocuments",
            name="trainee",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trainingdocuments",
            name="training_module",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
