# Generated by Django 5.0.7 on 2024-08-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Training",
            "0006_rename_documentdomain_trainingdocuments_document_domain_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainingdocuments",
            old_name="trainee",
            new_name="trainee_names",
        ),
        migrations.RenameField(
            model_name="trainingdocuments",
            old_name="training_module",
            new_name="training_module_name",
        ),
    ]
