# Generated by Django 5.0.7 on 2024-08-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0007_rename_trainee_trainingdocuments_trainee_names_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingdocuments",
            name="Trainingdate",
            field=models.CharField(default="date 000", max_length=50),
        ),
    ]
