# Generated by Django 5.0.7 on 2024-08-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0009_plannedtraining"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_marks", models.PositiveIntegerField()),
                ("average_marks", models.FloatField()),
                ("marks_per_module", models.JSONField()),
                ("count_of_exams", models.PositiveIntegerField()),
                ("date_of_exam", models.DateTimeField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Training.profile",
                    ),
                ),
                (
                    "training_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Training.trainingmodule",
                    ),
                ),
            ],
        ),
    ]
