# Generated by Django 5.0.7 on 2024-08-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0010_exam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="marks_per_module",
        ),
    ]
