# Generated by Django 5.0.7 on 2024-08-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0011_remove_exam_marks_per_module"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="average_marks",
        ),
    ]
